INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("100% Bran", "Nabisco");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("100% Natural Bran", "Quaker Oats");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("All-Bran", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("All-Bran with Extra Fiber", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Almond Delight", "Ralston Purina");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Apple Cinnamon Cheerios", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Apple Jacks", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Basic 4", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Bran Chex", "Ralston Purina");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Bran Flakes", "Post");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Cap'n'Crunch", "Quaker Oats");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Cheerios", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Cinnamon Toast Crunch", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Clusters", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Cocoa Puffs", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Corn Chex", "Ralston Purina");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Corn Flakes", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Corn Pops", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Count Chocula", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Cracklin' Oat Bran", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Cream of Wheat (Quick)", "Nabisco");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Crispix", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Crispy Wheat & Raisins", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Double Chex", "Ralston Purina");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Froot Loops", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Frosted Flakes", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Frosted Mini-Wheats", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Fruit & Fibre Dates; Walnuts; and Oats", "Post");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Fruitful Bran", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Fruity Pebbles", "Post");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Golden Crisp", "Post");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Golden Grahams", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Grape Nuts Flakes", "Post");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Grape-Nuts", "Post");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Great Grains Pecan", "Post");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Honey Graham Ohs", "Quaker Oats");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Honey Nut Cheerios", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Honey-comb", "Post");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Just Right Crunchy  Nuggets", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Just Right Fruit & Nut", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Kix", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Life", "Quaker Oats");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Lucky Charms", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Maypo", "American Home Food Products");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Muesli Raisins; Dates; & Almonds", "Ralston Purina");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Muesli Raisins; Peaches; & Pecans", "Ralston Purina");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Mueslix Crispy Blend", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Multi-Grain Cheerios", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Nut&Honey Crunch", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Nutri-Grain Almond-Raisin", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Nutri-grain Wheat", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Oatmeal Raisin Crisp", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Post Nat. Raisin Bran", "Post");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Product 19", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Puffed Rice", "Quaker Oats");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Puffed Wheat", "Quaker Oats");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Quaker Oat Squares", "Quaker Oats");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Quaker Oatmeal", "Quaker Oats");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Raisin Bran", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Raisin Nut Bran", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Raisin Squares", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Rice Chex", "Ralston Purina");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Rice Krispies", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Shredded Wheat", "Nabisco");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Shredded Wheat 'n'Bran", "Nabisco");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Shredded Wheat spoon size", "Nabisco");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Smacks", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Special K", "Kelloggs");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Strawberry Fruit Wheats", "Nabisco");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Total Corn Flakes", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Total Raisin Bran", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Total Whole Grain", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Triples", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Trix", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Wheat Chex", "Ralston Purina");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Wheaties", "General Mills");
INSERT INTO cereal_manufacturer (name, manufacturer) VALUES ("Wheaties Honey Gold", "General Mills");