INSERT INTO cereal_info (cereal_id, name, type) VALUES (1, "100% Bran", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (2, "100% Natural Bran", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (3, "All-Bran", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (4, "All-Bran with Extra Fiber", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (5, "Almond Delight", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (6, "Apple Cinnamon Cheerios", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (7, "Apple Jacks", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (8, "Basic 4", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (9, "Bran Chex", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (10, "Bran Flakes", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (11, "Cap'n'Crunch", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (12, "Cheerios", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (13, "Cinnamon Toast Crunch", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (14, "Clusters", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (15, "Cocoa Puffs", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (16, "Corn Chex", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (17, "Corn Flakes", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (18, "Corn Pops", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (19, "Count Chocula", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (20, "Cracklin' Oat Bran", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (21, "Cream of Wheat (Quick)", "H");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (22, "Crispix", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (23, "Crispy Wheat & Raisins", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (24, "Double Chex", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (25, "Froot Loops", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (26, "Frosted Flakes", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (27, "Frosted Mini-Wheats", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (28, "Fruit & Fibre Dates; Walnuts; and Oats", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (29, "Fruitful Bran", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (30, "Fruity Pebbles", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (31, "Golden Crisp", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (32, "Golden Grahams", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (33, "Grape Nuts Flakes", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (34, "Grape-Nuts", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (35, "Great Grains Pecan", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (36, "Honey Graham Ohs", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (37, "Honey Nut Cheerios", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (38, "Honey-comb", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (39, "Just Right Crunchy  Nuggets", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (40, "Just Right Fruit & Nut", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (41, "Kix", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (42, "Life", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (43, "Lucky Charms", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (44, "Maypo", "H");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (45, "Muesli Raisins; Dates; & Almonds", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (46, "Muesli Raisins; Peaches; & Pecans", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (47, "Mueslix Crispy Blend", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (48, "Multi-Grain Cheerios", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (49, "Nut&Honey Crunch", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (50, "Nutri-Grain Almond-Raisin", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (51, "Nutri-grain Wheat", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (52, "Oatmeal Raisin Crisp", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (53, "Post Nat. Raisin Bran", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (54, "Product 19", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (55, "Puffed Rice", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (56, "Puffed Wheat", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (57, "Quaker Oat Squares", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (58, "Quaker Oatmeal", "H");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (59, "Raisin Bran", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (60, "Raisin Nut Bran", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (61, "Raisin Squares", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (62, "Rice Chex", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (63, "Rice Krispies", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (64, "Shredded Wheat", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (65, "Shredded Wheat 'n'Bran", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (66, "Shredded Wheat spoon size", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (67, "Smacks", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (68, "Special K", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (69, "Strawberry Fruit Wheats", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (70, "Total Corn Flakes", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (71, "Total Raisin Bran", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (72, "Total Whole Grain", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (73, "Triples", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (74, "Trix", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (75, "Wheat Chex", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (76, "Wheaties", "C");
INSERT INTO cereal_info (cereal_id, name, type) VALUES (77, "Wheaties Honey Gold", "C");