INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("ann", 15, 1, "Where has this been all my life", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user1", 15, 2, "You should try it with jam!", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user2", 17, 1, "This cereal gets soggy really fast", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user3", 23, 1, "I simply have no words! It's truly...atrocious", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user4", 24, 1, "Only cereal heathens dislike this one", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user5", 28, 1, "Some things are just not meant to be", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("ann", 33, 1, "People are sleeping on milk first with this one", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user1", 15, 3, "how do you write a comment", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user2", 73, 1, ":)", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user3", 1, 1, "Everything about this is a mistake", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("oliver", 21, 1, "Love this cereal", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("oliver", 15, 4, "This cereal cured my acne!", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user6", 23, 2, "How dare you even call this cereal", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user6", 21, 2, "This cereal is such a slay", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user7", 19, 1, "Could be better", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user8", 17, 2, "I give it a 6/10", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user8", 35, 1, "I'd marry this cereal if I could", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user9", 26, 1, "This cereal slaps", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user10", 24, 2, "Could be improved", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user11", 24, 3, "This cereal rocks!", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user11", 1, 2, "This cereal makes me sad :(", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("lilian", 22, 1, "I got an A on a test after eating this cereal", '20230320');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user17", 2, 1, "I got food poisoning from this", '20230321');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user13", 8, 1, "I became a CS god after eating this cereal", '20230322');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user14", 15, 5, "*throws up*", '20230323');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user16", 2, 2, "yum yum in my tum", '20230324');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user15", 21, 2, "I got an F on a test after eating this cereal", '20230325');
INSERT INTO comment (user_name, cereal_id, comment_id, text, date) VALUES ("user12", 7, 1, "this cereal is life changing", '20230326');