INSERT INTO creates_club (club_id, user_name) VALUES (1, "admin");
INSERT INTO creates_club (club_id, user_name) VALUES (2, "admin");
INSERT INTO creates_club (club_id, user_name) VALUES (3, "ann");
INSERT INTO creates_club (club_id, user_name) VALUES (4, "user1");
INSERT INTO creates_club (club_id, user_name) VALUES (5, "oliver");
INSERT INTO creates_club (club_id, user_name) VALUES (6, "oliver");
INSERT INTO creates_club (club_id, user_name) VALUES (7, "user6");
INSERT INTO creates_club (club_id, user_name) VALUES (8, "user7");
INSERT INTO creates_club (club_id, user_name) VALUES (9, "lilian");